image: https://i.ytimg.com/vi/7NCLGnv_oZI/hqdefault.jpg
url: https://mzaini30.js.org/
title: Zen
description: Tulisan-tulisan tentang teknologi, kehidupan, dan lain-lain
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
permalink: /:title.html
author:
  twitter: zenia2020
